Prepare for 1.15+
cuberite/cuberite pull request #4858
Opened 2020-09-11 20:29 UTC by tigerw

* Reduces confusion when using overloaded operator< and priority_queue

2020-09-11 23:07 UTC, bearbin requested changes

2020-09-11 23:07 UTC, bearbin commented on src/ChunkSender.cpp
> +void cChunkSender::QueueSendChunkTo(int a_ChunkX, int a_ChunkZ, Priority a_Priority, cClientHandle * a_Client)
This function looks like it should behave wrongly with the new priority system. As is, it looks like queueing a chunk with lower priority than it already has will be taken forwards. At the very least, this needs a comment to explain what it's doing.

2020-09-11 23:07 UTC, bearbin commented on src/ChunkSender.cpp
> +void cChunkSender::QueueSendChunkTo(int a_ChunkX, int a_ChunkZ, Priority a_Priority, cChunkClientHandles a_Clients)
Same here.

2020-09-12 18:57 UTC, tigerw commented
Thanks!

2020-09-12 19:05 UTC, bearbin approved these changes
I'm not really sure that this PR reflects the createst effort-benefit ratio of all the things that could have be done, but it looks fine to me.

2020-09-12 19:08 UTC, tigerw commented
well I'm the one doing it xD

2020-09-12 19:10 UTC, peterbell10 approved these changes
Sure, why not.

2020-09-12 19:19 UTC, bearbin commented
Well, you go on about wanting to increase the development velocity, I just wanted to point out that this _probably_ isn't a feature the users have all been clamouring over  :slightly_smiling_face:

2020-09-12 19:27 UTC, tigerw commented
true, true, but developers are the users of the code, and every dev likes deleting code :D

2020-09-12 19:43 UTC, merged