Implement Dropspenser Hook
cuberite/cuberite pull request #4903
Opened 2020-09-20 13:30 UTC by KrystilizeNevaDies

Implemented a hook for dropspensing.
HOOK_DROPSPENSE

MyOnDropSpenser(World, DropSpenser, SlotNum)

When plugin callback returns true then dropspense is cancelled

How can i add documentation for this for [api.cuberite.com](https://api.cuberite.com)?

2020-09-20 13:36 UTC, peterbell10 requested changes
>How can i add documentation for this for api.cuberite.org?

Documentation goes in the APIDump plugin. For hooks, that's in `Server/Plugins/APIDump/Hooks/`.

2020-09-20 13:36 UTC, peterbell10 commented on src/Bindings/PluginManager.h
> +	bool CallHookKilled		      		  (cEntity & a_Victim, TakeDamageInfo & a_TDI, AString & a_DeathMessage);
Spaces for alignment:
```suggestion
	bool CallHookKilled                   (cEntity & a_Victim, TakeDamageInfo & a_TDI, AString & a_DeathMessage);
```

2020-09-20 13:47 UTC, KrystilizeNevaDies commented
Updated with API documentation

2020-09-20 13:50 UTC, bearbin commented on src/BlockEntities/DropSpenserEntity.cpp
> +		}
Indentation is off here as well.

2020-09-20 13:59 UTC, bearbin approved these changes

2020-09-20 15:06 UTC, bearbin commented on src/BlockEntities/DropSpenserEntity.cpp
> +	if (cPluginManager::Get()->CallHookDropSpense(*m_World, *this, SpenseSlot))
clang-tidy failed here, you need to include PluginManager in this file.

2020-09-20 21:42 UTC, bearbin requested changes

2020-09-21 12:24 UTC, KrystilizeNevaDies commented
How can i fix this travis-ci error?

`ERROR: Newly undocumented API symbols found:
cPluginManager.HOOK_DROPSPENSE (constant)
The command "./travisbuild.sh" exited with 1.
cache.2
store build cache`

2020-09-21 13:15 UTC, bearbin commented on Server/Plugins/APIDump/Classes/Plugins.lua
> +            HOOK_DROPSPENSE =
Indentation is off here again.

2020-09-21 13:16 UTC, bearbin commented
> How can i fix this travis-ci error?
> 
> `ERROR: Newly undocumented API symbols found: cPluginManager.HOOK_DROPSPENSE (constant) The command "./travisbuild.sh" exited with 1. cache.2 store build cache`

You just did, I told you how in the previous review :)

2020-09-21 13:24 UTC, KrystilizeNevaDies commented
> > How can i fix this travis-ci error?
> > `ERROR: Newly undocumented API symbols found: cPluginManager.HOOK_DROPSPENSE (constant) The command "./travisbuild.sh" exited with 1. cache.2 store build cache`
> 
> You just did, I told you how in the previous review :)

:)

2020-09-21 14:57 UTC, bearbin approved these changes

2020-09-21 15:31 UTC, merged