Doors: check power & toggle correctly
cuberite/cuberite pull request #4947
Opened 2020-09-28 21:11 UTC by tigerw

* Fixed upper half ignoring its updates
* Fixes #4945
* Fixed doors playing sound effects when they didn't actually toggle

2020-09-28 22:02 UTC, peterbell10 requested changes

2020-09-28 22:17 UTC, tigerw commented on src/Simulator/IncrementalRedstoneSimulator/DoorHandler.h
> -		// Use redstone data rather than block state so players can override redstone control
I checked, it all works! Don't take my word for it though, more testing appreciated

2020-09-28 22:37 UTC, peterbell10 commented on src/Simulator/IncrementalRedstoneSimulator/DoorHandler.h
> -		// Use redstone data rather than block state so players can override redstone control
Oh I didn't realise `0x02` was different from the door open meta. So this actually fixes the restart problem for doors, nice. Might be nice to give the meta extraction a named function, but not a big deal.

2020-09-28 22:37 UTC, peterbell10 approved these changes

2020-09-28 22:40 UTC, tigerw commented on src/Simulator/IncrementalRedstoneSimulator/DoorHandler.h
> -		// Use redstone data rather than block state so players can override redstone control
I'm putting all my hopes and dreams on blockstates

2020-09-28 22:40 UTC, merged

2020-09-29 10:59 UTC, blueyshark commented
Hi all. I uninstalled the DietPi Cuberite package and installed Cuberite via
`curl -sSfL https://download.cuberite.org | sh`

After running and entering my world, buttons are still only activating doors when placed by the doors lower halves. I hope this helps! Addtionally, my logs show:

> [11:56:21] Stack trace:
> [11:56:21]   Plugins/Core/functions.lua(130): GetWorldDifficulty
> [11:56:21]   Plugins/Core/core_worlds.lua(80): (no name)
> [11:56:21] Stack trace end
> [11:56:21] Error in <attached> calling function <callback>()
> [11:56:21] LUA: Plugins/Core/functions.lua:130: attempt to index global 'WorldsWorldDifficulty' (a nil value)
> [11:56:21] Stack trace:
> [11:56:21]   Plugins/Core/functions.lua(130): GetWorldDifficulty
> [11:56:21]   Plugins/Core/core_worlds.lua(80): (no name)
> [11:56:21] Stack trace end
> [11:56:21] Error in <attached> calling function <callback>()
> [11:56:25] LUA: Plugins/Core/functions.lua:130: attempt to index global 'WorldsWorldDifficulty' (a nil value)
> [11:56:25] Stack trace:
> [11:56:25]   Plugins/Core/functions.lua(130): GetWorldDifficulty
> [11:56:25]   Plugins/Core/core_worlds.lua(80): (no name)
> [11:56:25] Stack trace end
> [11:56:25] Error in <attached> calling function <callback>()
> [11:56:25] LUA: Plugins/Core/functions.lua:130: attempt to index global 'WorldsWorldDifficulty' (a nil value)
> [11:56:25] Stack trace:
> [11:56:25]   Plugins/Core/functions.lua(130): GetWorldDifficulty
> [11:56:25]   Plugins/Core/core_worlds.lua(80): (no name)
> [11:56:25] Stack trace end
> [11:56:25] Error in <attached> calling function <callback>()
> [11:56:27] LUA: Plugins/Core/functions.lua:130: attempt to index global 'WorldsWorldDifficulty' (a nil value)
> [11:56:27] Stack trace:
> [11:56:27]   Plugins/Core/functions.lua(130): GetWorldDifficulty
> [11:56:27]   Plugins/Core/core_worlds.lua(80): (no name)
> [11:56:27] Stack trace end
> [11:56:27] Error in <attached> calling function <callback>()
> [11:56:27] LUA: Plugins/Core/functions.lua:130: attempt to index global 'WorldsWorldDifficulty' (a nil value)
> [11:56:27] Stack trace:
> [11:56:27]   Plugins/Core/functions.lua(130): GetWorldDifficulty
> [11:56:27]   Plugins/Core/core_worlds.lua(80): (no name)
> [11:56:27] Stack trace end
> [11:56:27] Error in <attached> calling function <callback>()

2020-09-29 11:19 UTC, tigerw commented
Could you copy the complete server log? I'm interested in the lines that say something like

```
Log: [21:17:35] --- Started Log ---
Log: [21:17:35] Cuberite Travis clang  (id: WWW)
Log: [21:17:35] from commit XXX built at: YYY
```

2020-09-29 11:28 UTC, blueyshark commented
Complete Log as requested

>      [11:52:57] --- Started Log ---
>      [11:52:57] Cuberite Jenkins arm-linux-gnueabihf -DCMAKE_BUILD_TYPE=Release (master) (id: #80)
>      [11:52:57] from commit c9fbb43ac7a619f54b2de13bd59d37dbcc939d35 built at: Mon Sep 28 22:40:05 UTC 2020
>      [11:52:57] Creating new server instance...
>      [11:52:57] Reading server config...
>      [11:52:57] Starting server...
> Info [11:52:57] Compatible clients: 1.8.x-1.12.x
> Warn [11:52:57] WebServer: The server will run in unsecured HTTP mode.
> Info [11:52:57] Put a valid HTTPS certificate in file 'webadmin/httpscert.crt' and its corresponding private key to 'webadmin/httpskey.pem' (without any password) to enable HTTPS support
>      [11:52:57] Loaded 757 crafting recipes
> Warn [11:52:57] Cannot open file "Protocol/1.14.4/base.recipes.txt", no recipe book recipes will be available!
> Warn [11:52:57] Cannot open file "Protocol/1.13/base.recipes.txt", no recipe book recipes will be available!
>      [11:52:57] Loaded 1.12.2 380 recipe book
>      [11:52:57] Loaded 67 furnace recipes and 66 fuels
>      [11:52:57] Loaded 49 brewing recipes
>      [11:52:57] -- Loading Plugins --
> Warn [11:52:57] LUA: Plugins/Core/functions.lua:152: attempt to index global 'WorldsSpawnProtect' (a nil value)
> Warn [11:52:57] Stack trace:
> Warn [11:52:57]   Plugins/Core/functions.lua(152): LoadWorldSettings
> Warn [11:52:57]   Plugins/Core/main.lua(32): (no name)
> Warn [11:52:57]   [C](-1): ForEachWorld
> Warn [11:52:57]   Plugins/Core/main.lua(30): (no name)
> Warn [11:52:57] Stack trace end
> Warn [11:52:57] Error in <attached> calling function <callback>()
> Warn [11:52:57] LUA: Plugins/Core/functions.lua:152: attempt to index global 'WorldsSpawnProtect' (a nil value)
> Warn [11:52:57] Stack trace:
> Warn [11:52:57]   Plugins/Core/functions.lua(152): LoadWorldSettings
> Warn [11:52:57]   Plugins/Core/main.lua(32): (no name)
> Warn [11:52:57]   [C](-1): ForEachWorld
> Warn [11:52:57]   Plugins/Core/main.lua(30): (no name)
> Warn [11:52:57] Stack trace end
> Warn [11:52:57] Error in <attached> calling function <callback>()
>      [11:52:57] Initialised Core
>      [11:52:57] Initialized ChatLog v.3
>      [11:52:57] -- Loaded 2 Plugins --
>      [11:52:59] Preparing spawn (world_nether): 83.50% (334/400; 331.02 chunks / sec)
> Info [11:52:59] WebAdmin is running on port(s) 1339
>      [11:52:59] Startup complete, took 1800ms!
> Info [11:53:47] User fresh_turf authenticated with UUID d3f6c7f3791f4eb0b39b9032870abe92
> Info [11:53:47] Player fresh_turf has joined the game
> Warn [11:53:47] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:47] Stack trace:
> Warn [11:53:47]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:47] Stack trace end
> Warn [11:53:47] Error in <attached> calling function <callback>()
> Warn [11:53:47] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:47] Stack trace:
> Warn [11:53:47]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:47] Stack trace end
> Warn [11:53:47] Error in <attached> calling function <callback>()
> Warn [11:53:49] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:49] Stack trace:
> Warn [11:53:49]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:49] Stack trace end
> Warn [11:53:49] Error in <attached> calling function <callback>()
> Warn [11:53:49] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:49] Stack trace:
> Warn [11:53:49]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:49] Stack trace end
> Warn [11:53:49] Error in <attached> calling function <callback>()
> Warn [11:53:49] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:49] Stack trace:
> Warn [11:53:49]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:49] Stack trace end
> Warn [11:53:49] Error in <attached> calling function <callback>()
> Warn [11:53:49] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:49] Stack trace:
> Warn [11:53:49]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:49] Stack trace end
> Warn [11:53:49] Error in <attached> calling function <callback>()
> Warn [11:53:49] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:49] Stack trace:
> Warn [11:53:49]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:49] Stack trace end
> Warn [11:53:49] Error in <attached> calling function <callback>()
> Warn [11:53:49] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:49] Stack trace:
> Warn [11:53:49]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:49] Stack trace end
> Warn [11:53:49] Error in <attached> calling function <callback>()
> Warn [11:53:49] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:49] Stack trace:
> Warn [11:53:49]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:49] Stack trace end
> Warn [11:53:49] Error in <attached> calling function <callback>()
> Warn [11:53:49] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:49] Stack trace:
> Warn [11:53:49]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:49] Stack trace end
> Warn [11:53:49] Error in <attached> calling function <callback>()
> Warn [11:53:49] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:49] Stack trace:
> Warn [11:53:49]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:49] Stack trace end
> Warn [11:53:49] Error in <attached> calling function <callback>()
> Warn [11:53:49] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:49] Stack trace:
> Warn [11:53:49]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:49] Stack trace end
> Warn [11:53:49] Error in <attached> calling function <callback>()
> Warn [11:53:49] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:49] Stack trace:
> Warn [11:53:49]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:49] Stack trace end
> Warn [11:53:49] Error in <attached> calling function <callback>()
> Warn [11:53:49] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:49] Stack trace:
> Warn [11:53:49]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:49] Stack trace end
> Warn [11:53:49] Error in <attached> calling function <callback>()
> Warn [11:53:50] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:50] Stack trace:
> Warn [11:53:50]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:50] Stack trace end
> Warn [11:53:50] Error in <attached> calling function <callback>()
> Warn [11:53:50] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:50] Stack trace:
> Warn [11:53:50]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:50] Stack trace end
> Warn [11:53:50] Error in <attached> calling function <callback>()
> Warn [11:53:50] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:50] Stack trace:
> Warn [11:53:50]   Plugins/Core/worldlimiter.lua(8): (no name)
> Warn [11:53:50] Stack trace end
> Warn [11:53:50] Error in <attached> calling function <callback>()
> Warn [11:53:50] LUA: Plugins/Core/worldlimiter.lua:8: attempt to index global 'WorldsWorldLimit' (a nil value)
> Warn [11:53:50] Stack trace:
> Wa [...]

2020-09-29 11:41 UTC, KingCol13 commented
@blueyshark thanks for the log, you're unlucky because this binary was compiled just before @tigerw patched it. The binary being distributed now contains this patch, so if you run that command again in the same location it will be fixed :)

2020-09-29 11:42 UTC, bearbin commented
I'm still not exactly sure where the lua error is coming from, but this does highlight that we haven't updated the Core submodule to take into account the latest changes from its own repo. I'll put in a PR for that momentarily.

2020-09-29 11:43 UTC, bearbin commented
NVM, I was mistaken - Core actually was updated in this repo, just missing a CI change that isn't relevant to the main server.