Removed C style arrays from the BlockEntity folder
cuberite/cuberite pull request #5005
Opened 2020-10-20 11:29 UTC by tigerw

2020-10-25 07:53 UTC, 12xx12 requested changes
Code looks good.

I know it's a bit nitpicky, but I think we should update the variable names to the new NamingSceme when touching the code of older functions.
If you think otherwise dismiss this review

2020-10-28 20:49 UTC, tigerw commented
yes I agree. Waiting on #4979 to see if I should close this or not.

2022-10-29 04:56 UTC, 12xx12 requested changes
Here I am after a long time going through pull requests.

There is another thing I saw

2022-10-29 04:56 UTC, 12xx12 commented on src/BlockEntities/BrewingstandEntity.cpp
>  		for (int i = 0; i < 3; i++)
Why not use a `std::size_t` as the iteration variable

2022-10-29 04:56 UTC, 12xx12 commented on src/BlockEntities/BrewingstandEntity.cpp
> +			m_Results[static_cast<size_t>(i)].Clear();
Same here

2022-10-29 04:56 UTC, 12xx12 commented on src/BlockEntities/BrewingstandEntity.cpp
> +			m_Results[static_cast<size_t>(i)] = Recipe->Output.CopyOne();
And here

2022-11-02 00:17 UTC, tigerw commented
what a dereliction of duty, i've left this for two years! thanks for the comments :D

2023-03-21 08:39 UTC, 12xx12 commented
Fixed it myself and updated it to master

2023-03-21 08:51 UTC, 12xx12 commented
I think I crashed the CI. Again.... xD

2023-03-21 22:43 UTC, bearbin commented
Apologies for the broken CI, it's not you it's just OVH's broken openStack implementation. I really ought to sort it out, but never got the time. Maybe soon :)  I have poked it so the queued up builds should be going now.

2023-03-21 22:44 UTC, bearbin approved these changes
Fine, GTM when the build passes.

2023-03-22 10:20 UTC, merged