Pull Request Resolving Issue #5166
cuberite/cuberite pull request #5188
Opened 2021-04-13 00:36 UTC by nshah25

Hello, I am working on issue #5166 and have added //to_lua and //end_lua tags in the Statistics.h file and updated the APIDesc.lua file with the changes made. This is my first pull request, so please let me know if I need to do anything else! Thanks!

2021-04-13 22:28 UTC, 12xx12 commented
Hi and welcome to the project.
Thank you for the PR!

A small tip reguarding the checkstyle: Set up you IDE to use tabs as indentation.
I think you'll need to exportt the statistic enum to the lua API also to acess the values.

2021-04-13 22:34 UTC, 12xx12 requested changes

2021-04-13 22:34 UTC, 12xx12 commented on Server/Plugins/APIDump/APIDesc.lua
> +							Type = "<unknown>"
This should be the enum value. Look at the other enums in the APIDesc file

2021-04-13 22:34 UTC, 12xx12 commented on Server/Plugins/APIDump/APIDesc.lua
> +							Type = "<unknown>"
```suggestion
							Type = "number"
```

2021-04-13 22:34 UTC, 12xx12 commented on Server/Plugins/APIDump/APIDesc.lua
> +					},
```suggestion
				
```

2021-04-13 22:34 UTC, 12xx12 commented on Server/Plugins/APIDump/APIDesc.lua
> +						}
same here

2021-04-13 22:34 UTC, 12xx12 commented on Server/Plugins/APIDump/APIDesc.lua
> +						Type = "StatValue",
```suggestion
						Type = "number",
```

2021-04-14 01:20 UTC, nshah25 commented
Thank you so much! This was really helpful and my partner and I are both really excited to help contribute to Cuberite!

2021-04-14 01:21 UTC, closed without merging