Fixing grass not generating below trees
cuberite/cuberite pull request #5199
Opened 2021-04-20 14:03 UTC by 12xx12

Fixes #5135

2021-04-20 15:07 UTC, bearbin requested changes

2021-04-20 15:07 UTC, bearbin commented on src/Generating/FinishGen.cpp
> +				BlockBelow = a_ChunkDesc.GetBlockType(x, y - 1, z);
This needs a bounds check, at least.

2021-04-20 15:09 UTC, 12xx12 commented on src/Generating/FinishGen.cpp
> +				BlockBelow = a_ChunkDesc.GetBlockType(x, y - 1, z);
yeah - you're right

2021-04-20 15:29 UTC, bearbin approved these changes

2021-04-20 19:28 UTC, tigerw commented
can we re-order the finishers so the grass generator runs before trees are planted?

2021-04-20 19:41 UTC, 12xx12 commented
that would work too

2021-04-20 22:49 UTC, bearbin commented
I can imagine there would be weird edge cases doing it the other way too, any particular reason not to do it this way @tigerw?

2021-04-21 06:55 UTC, 12xx12 commented
Negative:
I am not sure what happens if the generator tries to place a tree where already grass is

Positive:
Less performance impact

2021-04-21 10:54 UTC, tigerw commented
Performance mainly, ideally we'd reduce Y-major searching because the stride is 256 elements.

2021-04-23 12:53 UTC, bearbin commented
I suggest we merge this unless somebody wants to do a performance test then.

2021-04-23 18:59 UTC, tigerw commented
OK, I can investigate reordering later then.

2021-04-23 19:00 UTC, merged