Repaired Hoppers Treating Chests as two entities
cuberite/cuberite pull request #5202
Opened 2021-04-22 02:27 UTC by npresley0506

Hoppers used to treat double chests as two separate entities and would only pull from one side and deposit in one side. This has been repaired and the hopper now treats the chests as a solid entity. However, this uncovered an issue in that the hopper does not place items on already existing stacks, but will always place them in the first open spot of the chest. This is most likely due to an issue with MoveItemsToGrid and I will open a bug request for it if I can and try to work on it.

Please let me know if you run into any issues with the repairs and I'll do my best to fix them. Any feedback is welcome!

2021-04-22 08:58 UTC, 12xx12 requested changes
Gameplay is good.

Code seems fine 👍 

Mostly style stuff:
- Your IDE seems to change line ends please undo those (see line 380, 385,...)
- We changed the style of local variables to be capitalized. On some old code this is not the case and we try to upgrade it piece by piece. This is such a case could you do this please?

2021-04-22 08:58 UTC, 12xx12 commented on src/BlockEntities/HopperEntity.cpp
> +#include <iostream>
There is something left

2021-04-22 08:58 UTC, 12xx12 commented on src/BlockEntities/HopperEntity.cpp
> +		{0, 1, -1},
```suggestion
		{ 1, 1,  0},
		{-1, 1,  0},
		{ 0, 1,  1},
		{ 0, 1, -1},
```

The spaces improved readability. Same as below

2021-04-22 08:58 UTC, 12xx12 commented on src/BlockEntities/HopperEntity.cpp
> +		auto chest = static_cast<cChestEntity *>(
```suggestion
		auto SideChest = static_cast<cChestEntity *>(
```

Maybe rename the variable for better readabilty. This is a bit confusing

2021-04-22 08:58 UTC, 12xx12 commented on src/BlockEntities/HopperEntity.cpp
> +		auto chestAbsCoords = neighbor->RelativeToAbsolute(otherHalfRelCoord);
```suggestion
		auto OtherHalfAbsCoords = neighbor->RelativeToAbsolute(OtherHalfRelCoord);
```

2021-04-22 09:12 UTC, 12xx12 commented
And please update the branch to master

2021-04-22 11:31 UTC, 12xx12 commented
Oh - I just noticed you are new to the project. Hi and welcome.
Please add yourself to the CONTRIBUTORS file due to copirght reasons. (and to be included to the newsletter :D)

2021-04-22 11:32 UTC, bearbin requested changes
Hi @npresley0506, thanks for taking the time to open this PR and fix the issue. 

Further to @12xx12's comment, you need to revert all of the unrelated formatting changes so this PR is just the code that you are actually changing here. Other than a bit of potential for simplification, the business logic looks fine so once that's done this could be merged in.

You also need to add your name to the CONTRIBUTORS file to indicate that you accept releasing your code under the correct license.

2021-04-22 11:32 UTC, bearbin commented on src/BlockEntities/HopperEntity.cpp
>  			}
The check for x versus z equivalency is pointless here and just makes the code longer - if you change the inner if condition to be `if ((neighborAbsCoord.x > chestPos.x) || (neighborAbsCoord.z > chestPos.z))` you could then remove the outer if and save half the code.

2021-04-22 13:01 UTC, tigerw commented
Haven't looked at the code but cChestEntity has a m_Neighbour field, representing the other half, if that helps.

2021-04-22 13:23 UTC, 12xx12 commented
Why do it easy if there is a more complex solution 😄

2021-04-22 15:00 UTC, npresley0506 commented
Thanks for the feedback everyone, I think I fixed the style issues and I condensed the logic from the MoveItemsFromChest. That's what I get for coding so late.

I think I managed to get everything, and stopped my IDE from being weird about lines, but if there's anything I missed let me know.

2021-04-22 15:09 UTC, bearbin reviewed
Looks fine now, I'll let the other two reviewers have a look to make sure their issues were addressed :)

2021-04-22 15:10 UTC, 12xx12 reviewed
One teeeny tiny thing

2021-04-22 15:10 UTC, 12xx12 commented on src/BlockEntities/HopperEntity.cpp
> +			FLOGWARNING("{0}: A chest entity was not found where expected, at {1} " "({2}, {3}})", __FUNCTION__, a_Coords + ofs, ofs.x, ofs.z);
```suggestion
			FLOGWARNING("{0}: A chest entity was not found where expected, at {1} ({2}, {3}})", __FUNCTION__, a_Coords + ofs, ofs.x, ofs.z);
```

2021-04-22 15:14 UTC, 12xx12 commented
That `m_Neighbour` thing is not adressed. This will improve performance (I think)

2021-04-22 16:52 UTC, npresley0506 commented
m_Neighbour is a private variable of cChestEntity, I'd have to make a function to get to that if that's alright?

2021-04-22 17:04 UTC, bearbin commented
Yes, adding a getter function should be fine. Just make sure it's not exported to lua.

2021-04-22 19:37 UTC, npresley0506 commented
Third times the charm

2021-04-22 21:58 UTC, bearbin commented on src/BlockEntities/ChestEntity.h
> +	cChestEntity * ReturnNeighbour();
This should be GetNeighbour (but +1 for the proper spelling of neightbour :))

2021-04-22 22:04 UTC, npresley0506 commented
my bad, should be good now, thanks for the patience haha

2021-04-22 22:06 UTC, bearbin approved these changes
No, thank you for your persistence :)

2021-04-23 11:06 UTC, 12xx12 approved these changes

2021-04-23 12:51 UTC, merged