Uninitialised values fix
cuberite/cuberite pull request #5570
Opened 2024-07-01 23:38 UTC by solvictor

Prevent some conditional jumps on uninitialised values. Found with valgrind in the terrain generator and Client Handler.

2024-07-02 13:03 UTC, mjagdis commented
Is that a real problem or just something that valgrind needs some help with? The Floor array are outputs from CalcFloorFrac as are how much of them are used. Any uninitialized part should be irrelevant.

If you really need them fully initialized it might be nicer to say, "int FloorX[MAX_SIZE] = { };" instead of using memset.

2024-07-02 14:54 UTC, solvictor commented
Can someone help me figure out why Windows-x64-Debug is not passing ? Everything looks good.

2024-07-02 18:40 UTC, bearbin commented
Not sure why it crashed, maybe the build agent got GCd or something. Reran and it worked :)

2024-07-02 18:41 UTC, bearbin requested changes
Looks like a reasonable change. Please could you add your name in the correct alpha-sorted position to the CONTRIBUTORS file to recognise your contribution under the correct license?

2024-07-02 22:51 UTC, bearbin reviewed
This looks sensible, I was just going to merge, but thinking again about what @mjagdis said, if we're actually getting uninitialised reads from these vars there's probably something wrong with the algorithm or its usage somewhere and we ought to look into that.

Do you have a reproducible test case that will trigger these uninitialised reads? I'd like to take a look and step through the code and debug what's actually happening - OFC feel free to do this yourself as well!

2024-07-02 22:53 UTC, bearbin commented
I was referring to the noise change above, client handle change looks fine. If you could get a nice minimal example (maybe just make up a cpp file that uses the noise gen to trigger the read) that would be ideal!

2024-07-02 23:08 UTC, solvictor commented
To reproduce the bug you can start a server with an empty world, the bug occurs when creating new chunks. To debug it you must compile in Debug mode and let the arrays uninitialized and launch the server with `valgrind --track-origins=yes ./Cuberite`. I don't know how the algorithm is supposed to work or what part of it is accessing theese values that are not supposed to be accessed.

2024-07-22 19:10 UTC, iamnoksio commented
it's a perfect temp fix, push it

2024-07-22 21:54 UTC, mjagdis commented
> it's a perfect temp fix, push it

The m_ProxyConnection bit, yes - it's a proper fix.

The Floor bit, no. There is no such thing as a "temp fix" and applying this would hide the only thing that suggests anything might be wrong here. So either someone needs to explain why there are accesses to Floor beyond a_Size and why those accesses should return 0 rather than some other value or someone needs to figure out what actually needs fixing.

I'd split it in two, a patch and an issue.

2024-07-24 14:58 UTC, mjagdis commented
Forget the issue. See #5576

2024-07-27 22:07 UTC, madmaxoft requested changes

2024-07-27 22:07 UTC, madmaxoft commented on src/Noise/InterpolNoise.h
>  		CalcFloorFrac(a_SizeX, a_StartX, a_EndX, FloorX, FracX, SameX, NumSameX);
These are not good changes. They hurt performance by needlessly filling the arrays with zeroes and then immediately overwriting the values with the proper calculated numbers.
Also the `CalcFloorFrac` call is tightly coupled to the declarations, the additional empty line breaks this logical tie.

As @mjagdis already pointed out, this needs a deeper fix, which he even provided, so please remove this from the PR.

2024-08-05 08:46 UTC, madmaxoft requested changes

2024-08-05 08:46 UTC, madmaxoft commented on src/Noise/InterpolNoise.h
Changes to this file should be dropped from the PR altogether. Then it's fine to go.

2024-08-07 10:06 UTC, madmaxoft approved these changes
Awesome, thanks

2024-08-29 22:05 UTC, solvictor commented
@bearbin Can you review please ?

2024-09-08 21:18 UTC, merged

2024-09-08 21:19 UTC, madmaxoft commented
I took the liberty of merging it, the change itself is tiny so it's okay, and Bearbin's request was met.

2024-09-08 21:45 UTC, iamnoksio commented
FINALLY DAMN, MERGING AFTER MONTHS IS CRAZY