Fix access to uninitialized space
cuberite/cuberite pull request #5576
Opened 2024-07-24 14:56 UTC by mjagdis

Sooo...

CalcFloorFrac sets up the Floor arrays using a_Size element and returning Same and NumSame. We then loop over the x, y, z dimensions from 0 to NumSame doing a Cell.Generate followed by a Cell.Move. The Cell.Generate does the real work, the Cell.Move sets up for the next iteration. But for the last iteration of each loop there is no next and the Floor[To] passed to Cell.Move is off the end of the space used in Floor. For the last iterations it looks like we should be wrapping back to the beginning of the Floor arrays. It doesn't seem to make an observable difference (it's all noise :-) ). It just avoids the dodgy access.

2024-07-27 22:12 UTC, madmaxoft requested changes
Good catch. However, when re-reading the code, it seems we can skip the `Move` calls at the end of each `for` loop completely.
Also, don't forget there's a `Generate2D` function as well using the same approach, needing the same fix.

2024-07-28 14:44 UTC, madmaxoft commented
The way I see it, at the end of an inner loop there is a `Move` operation (line 444), followed by another `Move` just below that inner loop (line 447). So when the loop terminates, the inner `Move` should not be needed.

2024-07-28 22:04 UTC, mjagdis commented
It's not obvious to me that the second Move cancels out the effect of the first. The arguments are different and Move uses all of them to generate the next m_WorkRnds so skipping a move would seem to change the sequence. Mind you, so does injecting an arbitrary value. And I haven't looked in detail at Move. And I don't even know if it matters? It's all, literally, noise, isn't it?

2024-07-30 10:17 UTC, madmaxoft commented
`Move` just sets up the internal variables so that the call to `Generate` has everything set up correctly; calling it should reset the entire internal state based only on the params, so calling it twice is the same as calling it only the second time.
Basically, it calculates the noise values at the integral coords, with `Generate` then interpolating between those at the non-integral coords.

2024-08-07 10:07 UTC, mjagdis commented
Well, Move seems to use state saved by the prior call as well as the params. But I can't see that it matters so...

2024-08-07 19:07 UTC, madmaxoft commented
It only uses that state as a cache, not to recalculate the same noise values over and over again if they are already present.

2024-08-10 15:19 UTC, madmaxoft requested changes
The construct is somewhat unexpected, so it warrants some comments around it.

2024-08-10 15:19 UTC, madmaxoft commented on src/Noise/InterpolNoise.h
> +					if (++x < NumSameX)
```suggestion
					if (++x < NumSameX)
					if (++x < NumSameX)  // Call Move() everytime except for the last loop iteration
```
Etc. in respective locations

2024-09-08 21:16 UTC, madmaxoft approved these changes

2024-09-08 21:16 UTC, madmaxoft commented
Sorry for the long wait.

2024-11-01 22:17 UTC, merged