feat: add detached flag to run in foreground with detached stdin
cuberite/cuberite pull request #5592
Opened 2024-11-22 06:54 UTC by superewald

Add a cli flag to skip listening to stdin (cRoot::HandleInput) to allow running the process in foreground but with detached tty. This is necessary to run cuberite in containers without the need of a detached tty.

Fixes #3726.

2024-11-22 07:08 UTC, MightyFilipns commented
Fix the style issues and add yourself to the CONTRIBUTORS file

2024-11-22 12:34 UTC, superewald commented
Sorry I should have recognize this by myself. Fixed now.

2024-12-01 12:54 UTC, bearbin commented
Does the existing `-d` flag not do this already?

2025-01-01 20:25 UTC, superewald commented
Sorry for the late response, somehow I wasn't notified about updates in this PR.
I moved the check into the HandleInput where g_RunAsService is checked already. Not sure this is what you wanted tho (but it makes sense either way).

2025-01-01 21:14 UTC, bearbin commented on CONTRIBUTORS
> +SuperEwald
This is alpha-sorted, you need to be in the middle.

2025-01-01 21:14 UTC, bearbin requested changes
Tiny thing, looks good now though :)

2025-01-03 14:44 UTC, bearbin approved these changes

2025-01-03 14:45 UTC, merged